disabled = false
languageCode = "zh-tw"
languageName = "繁體中文"
weight = 1
title = "ANCuber's Website"

[params]
    displayName = "繁體中文"
    isoCode = "zh-tw"
    rtl = false
    dateFormat = "2006-01-02"
    # logo = "img/pikachu.png"
    # secondaryLogo = "img/pikachu.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
    name = "Anson Lai"
    email = "ansona1131@gmail.com"
    image = "img/author.jpeg"
    imageQuality = 96
    headline = "歡迎！"
    # bio = "Hi, I am currently a college student majoring CS at NTU."
