baseURL = 'https://ANCuber.github.io/'
languageCode = 'en-us'
title = "ANCuber's Blog"
theme = 'erblog'

[params]
    author = "Anson Lai"
    badge = "blue"
    index_posts_num = 5
    google_search = true
    
